name: Release build

on: 
  workflow_dispatch:
    inputs:
      tags:
        description: 'tags to create build'

jobs:
  build:
    runs-on: windows-latest
    permissions: write-all
    steps:
    - uses: actions/checkout@v4
      with:
        ref: master    
    - name: Build
      run:
        docker build . -t judge-server
    - name: Get file sizes
      run: |
        gci -rec -file|%{"$($_.Fullname) $($_.Length)"} >filelist.txt
    - name: Archive Release packages
      shell: bash
      run: |
        "/c/Program Files/7-Zip/7z.exe" a -m0=lzma2 -mx t0.7z "."
    - name: Archive filelist
      shell: bash
      run: |
        "/c/Program Files/7-Zip/7z.exe" a -m0=lzma2 -mx t1.7z "filelist.txt"
    - name: create release and upload assets
      uses: softprops/action-gh-release@v2
      with:
        files: |
          t0.7z
          t1.7z
        tag_name: ${{ github.event.inputs.tags }}
