name: Release build

on: 
  workflow_dispatch:
    inputs:
      tags:
        description: 'tags to create build'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
    - uses: actions/checkout@v4
      with:
        ref: master    
        submodules: recursive
    - name: Build
      run:
        docker build . -t judge-server
    - name: Get file sizes
      run: |
        ls -l > filelist.txt
    - name: Archive filelist
      shell: bash
      run: |
        tar cvzf t1.7z "filelist.txt"
    - name: Archive Release packages
      shell: bash
      run: |
        mkdir artefacts
        tar -zcvf artefacts/t0.7z --exclude=./artefacts .
    - name: create release and upload assets
      uses: softprops/action-gh-release@v2
      with:
        files: |
          artefacts/t0.7z
          t1.7z
        tag_name: ${{ github.event.inputs.tags }}
